const express=require("express");
const helmet=require("helmet");
const cors=require("cors");
const rateLimit=require("express-rate-limit");
const {Pool}=require("pg");
const crypto=require("crypto");
const {validateUpload,buildQuarantineKey}=require("./intake");

const app=express();
app.use(helmet());
app.use(cors({origin:process.env.CORS_ORIGIN||"http://localhost:3000"}));
app.use(express.json({limit:"2mb"}));

const pool=new Pool({
  connectionString:process.env.DATABASE_URL,
  ssl:process.env.NODE_ENV==="production"?{rejectUnauthorized:true}:false
});

const intakeLimiter=rateLimit({
  windowMs:15*60*1000,
  limit:30,
  standardHeaders:"draft-8",
  legacyHeaders:false
});

app.get("/health",(_req,res)=>res.json({ok:true,phase:20}));

/*
  This endpoint creates an intake record only.
  Actual binary transfer should go directly to private object storage using
  a short-lived signed upload URL. Do not send large APKs through Express.
*/
app.post("/api/intake/create",intakeLimiter,async(req,res)=>{
  const originalName=String(req.body?.originalName||"");
  const contentType=String(req.body?.contentType||"");
  const sizeBytes=Number(req.body?.sizeBytes||0);
  const maxBytes=Number(process.env.MAX_UPLOAD_BYTES||524288000);

  const check=validateUpload({originalName,contentType,sizeBytes,maxBytes});
  if(!check.valid)return res.status(400).json({error:"Upload rejected",issues:check.issues});

  const id=crypto.randomUUID();
  const objectKey=buildQuarantineKey(id,originalName);

  try{
    const {rows}=await pool.query(`
      INSERT INTO upload_assets
        (id,original_name,object_key,content_type,size_bytes,status,scan_status)
      VALUES($1,$2,$3,$4,$5,'QUARANTINED','QUEUED')
      RETURNING id,original_name,object_key,status,scan_status,created_at
    `,[id,originalName,objectKey,contentType,sizeBytes]);

    // Production: return a short-lived signed PUT URL generated by your
    // object-storage SDK. Never expose storage credentials to the browser.
    res.status(201).json({
      upload:rows[0],
      next:"Upload binary to private quarantine storage, then enqueue scanning."
    });
  }catch(err){
    console.error(err);
    res.status(500).json({error:"Could not create intake record"});
  }
});

app.get("/api/intake/:id",async(req,res)=>{
  try{
    const {rows}=await pool.query(`
      SELECT id,original_name,content_type,size_bytes,sha256,status,
             scan_status,metadata,created_at,updated_at
      FROM upload_assets WHERE id=$1
    `,[req.params.id]);
    if(!rows[0])return res.status(404).json({error:"Upload not found"});
    res.json({upload:rows[0]});
  }catch(err){
    console.error(err);
    res.status(500).json({error:"Could not load upload"});
  }
});

app.listen(process.env.PORT||4000,()=>console.log("CrowMods Phase 20 Intake API running"));
