const express=require("express"); const helmet=require("helmet"); const cors=require("cors"); const {Pool}=require("pg");
const {rollup}=require("./percentiles"); const {applyDeadband}=require("./calibration-deadband"); const {buildManifest}=require("./export-manifest"); const {retentionDecision}=require("./retention");
const app=express(); app.use(helmet()); app.use(cors()); app.use(express.json({limit:"4mb"}));
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==="production"?{rejectUnauthorized:true}:false});
app.get("/health",(_q,s)=>s.json({status:"healthy",phase:132}));
app.get("/ready",async(_q,s)=>{try{await pool.query("SELECT 1");s.json({ready:true})}catch{s.status(503).json({ready:false})}});
app.post("/api/security/worker/audit-link",async(req,res)=>{try{const q=await pool.query(`SELECT id,worker_key,operation,expected_version,committed_version,result FROM worker_transaction_audit WHERE worker_key=$1 ORDER BY created_at DESC LIMIT 100`,[req.body.workerKey]);res.json({count:q.rowCount,events:q.rows})}catch{res.status(500).json({error:"audit_unavailable"})}});
app.post("/api/security/delegation/retry-percentiles",async(req,res)=>{const r=rollup(req.body.samples||[]);try{await pool.query(`INSERT INTO retry_percentile_rollups(run_key,sample_count,p50_ms,p95_ms,p99_ms) VALUES($1,$2,$3,$4,$5) ON CONFLICT(run_key) DO UPDATE SET sample_count=EXCLUDED.sample_count,p50_ms=EXCLUDED.p50_ms,p95_ms=EXCLUDED.p95_ms,p99_ms=EXCLUDED.p99_ms,updated_at=NOW()`,[req.body.runKey||"unknown",r.sampleCount,r.p50Ms,r.p95Ms,r.p99Ms])}catch{}res.json(r)});
app.post("/api/security/risk/calibration-deadband",async(req,res)=>{const r=applyDeadband({action:req.body.action,expandThreshold:Number(req.body.expandThreshold)||0,shrinkThreshold:Number(req.body.shrinkThreshold)||0,consecutiveExpand:Number(req.body.consecutiveExpand)||0,consecutiveShrink:Number(req.body.consecutiveShrink)||0,requiredCycles:Number(req.body.requiredCycles)||3,windowSize:Number(req.body.windowSize)||100,minWindow:Number(req.body.minWindow)||50,maxWindow:Number(req.body.maxWindow)||1000});try{await pool.query(`INSERT INTO calibration_deadbands(model_key,expand_threshold,shrink_threshold,consecutive_expand,consecutive_shrink,last_action,window_size) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(model_key) DO UPDATE SET consecutive_expand=EXCLUDED.consecutive_expand,consecutive_shrink=EXCLUDED.consecutive_shrink,last_action=EXCLUDED.last_action,window_size=EXCLUDED.window_size,updated_at=NOW()`,[req.body.modelKey||"default",Number(req.body.expandThreshold)||0,Number(req.body.shrinkThreshold)||0,r.consecutiveExpand,r.consecutiveShrink,r.action,r.windowSize])}catch{}res.json(r)});
app.post("/api/security/governance/alert/export-manifest",async(req,res)=>{try{const r=buildManifest({reviewer:req.body.reviewer,events:req.body.events||[]});await pool.query(`INSERT INTO export_manifests(reviewer,payload_hash,manifest_hash,event_count) VALUES($1,$2,$3,$4)`,[r.reviewer,r.payloadHash,r.manifestHash,r.eventCount]);res.json(r)}catch{res.status(400).json({error:"invalid_manifest"})}});
app.post("/api/security/governance/retention-check",(req,res)=>res.json(retentionDecision({createdAt:req.body.createdAt,retentionDays:Number(req.body.retentionDays),now:req.body.now||new Date()})));
app.get("/api/security/phase132-dashboard",async(_q,res)=>{try{const [a,p,d,e]=await Promise.all([pool.query(`SELECT COUNT(*)::int count FROM worker_transaction_audit WHERE created_at>NOW()-INTERVAL '30 days'`),pool.query(`SELECT COUNT(*)::int count FROM retry_percentile_rollups`),pool.query(`SELECT COUNT(*)::int count FROM calibration_deadbands WHERE last_action='HOLD'`),pool.query(`SELECT COUNT(*)::int count FROM export_manifests WHERE created_at>NOW()-INTERVAL '30 days'`)]);res.json({transactionAudits30d:a.rows[0].count,retryRollups:p.rows[0].count,heldCalibrations:d.rows[0].count,signedManifests30d:e.rows[0].count})}catch{res.status(500).json({error:"dashboard_unavailable"})}});
if (!process.env.CROWMODS_INTEGRATED) app.listen(process.env.PORT||4000,()=>console.log("CrowMods Phase 132 API running"));


module.exports = app;
